# Generated by Django 4.2.1 on 2023-10-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_order_user_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='place',
        ),
    ]
