# Generated by Django 4.2.1 on 2023-10-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_payment_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
